name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check and format files using the black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: "."
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --exit-code --staged; then
            echo "No changes to commit"
          else
            git commit -m ":art: Format Python code with psf/black"
            git push
          fi
